#!/usr/bin/env bash
mvn \
    -Dhr.restapi.url=${REST_API_URL} \
    -Dhr.website.url=${FRONTEND_URL} \
    -Dhr.regular.username=${REGULAR_USERNAME} \
    -Dhr.regular.password=${REGULAR_PASSWORD} \
    -Dtest=RunCukesTest \
    -Dwebdriver.timeouts.implicitlywait=15000 \
    -Dcukes.config.file=config.properties \
    -Dwebdriver.remote.driver=chrome \
    -Dchrome.switches=\"--proxy-server=$1:8080\" \
    -Dwebdriver.remote.url=http://selenium-hub:4444/wd/hub \
    clean test